/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ApiResourceModel: typeof import('./app/services/api/models/ApiResourceModel')['ApiResourceModel']
  const EmployeeModel: typeof import('./app/modules/employee/models/index')['EmployeeModel']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useAppDispatch: typeof import('./app/store/hooks/useAppDispatch')['useAppDispatch']
  const useAppSelector: typeof import('./app/store/hooks/useAppSelector')['useAppSelector']
  const useCallback: typeof import('react')['useCallback']
  const useConfirmModal: typeof import('./app/modules/employee/hooks/useConfirmModal')['useConfirmModal']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useEmployeeActions: typeof import('./app/modules/employee/hooks/useEmployeeActions')['useEmployeeActions']
  const useEmployeeFilter: typeof import('./app/modules/employee/hooks/useEmployeeFilter')['useEmployeeFilter']
  const useEmployeeList: typeof import('./app/modules/employee/hooks/useEmployeeList')['useEmployeeList']
  const useEmployeeStorageService: typeof import('./app/modules/employee/hooks/useEmployeeStorageService')['useEmployeeStorageService']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AppConfigInterface } from './app/interfaces/AppConfigInterface'
  import('./app/interfaces/AppConfigInterface')
  // @ts-ignore
  export type { AppNavigationInterface } from './app/interfaces/AppNavigationInterface'
  import('./app/interfaces/AppNavigationInterface')
  // @ts-ignore
  export type { ChildrenType, LayoutProps, MenuItem, HorizontalNavigationProps, FooterProps } from './app/interfaces/LayoutInterface'
  import('./app/interfaces/LayoutInterface')
  // @ts-ignore
  export type { ReduxSyncInterface } from './app/interfaces/ReduxSyncInterface'
  import('./app/interfaces/ReduxSyncInterface')
  // @ts-ignore
  export type { EmployeeCreateApiPayloadInterface } from './app/modules/employee/interfaces/EmployeeCreateApiPayloadInterface'
  import('./app/modules/employee/interfaces/EmployeeCreateApiPayloadInterface')
  // @ts-ignore
  export type { EmployeeFilterInterface } from './app/modules/employee/interfaces/EmployeeFilterInterface'
  import('./app/modules/employee/interfaces/EmployeeFilterInterface')
  // @ts-ignore
  export type { EmployeeInterface } from './app/modules/employee/interfaces/EmployeeInterface'
  import('./app/modules/employee/interfaces/EmployeeInterface')
  // @ts-ignore
  export type { StateInterface } from './app/modules/employee/interfaces/StateInterface'
  import('./app/modules/employee/interfaces/StateInterface')
  // @ts-ignore
  export type { ApiErrorDataInterface } from './app/services/api/interfaces/ApiErrorDataInterface'
  import('./app/services/api/interfaces/ApiErrorDataInterface')
  // @ts-ignore
  export type { ApiResourceInterface } from './app/services/api/interfaces/ApiResourceInterface'
  import('./app/services/api/interfaces/ApiResourceInterface')
  // @ts-ignore
  export type { ApiResponseInterface } from './app/services/api/interfaces/ApiResponseInterface'
  import('./app/services/api/interfaces/ApiResponseInterface')
  // @ts-ignore
  export type { EmployeeModel } from './app/modules/employee/models/EmployeeModel'
  import('./app/modules/employee/models/EmployeeModel')
  // @ts-ignore
  export type { ApiResourceModel } from './app/services/api/models/ApiResourceModel'
  import('./app/services/api/models/ApiResourceModel')
  // @ts-ignore
  export type { ConfirmModalState } from './app/modules/employee/hooks/modal.types'
  import('./app/modules/employee/hooks/modal.types')
}
